language: php

php:
    - 5.6
    - 7.0

before_script:
    - touch .env
    - echo "APP_KEY=SmduSUaF1KAAwhRIP6yLHgw0KzebWC6Z" >> .env
    - echo "DB_CONNECTION=sqlite" >> .env
    - touch database/database.sqlite
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - php artisan key:generate
    - php artisan migrate --database=testing --force
script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success: